# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf14140d26c0df039621e12530365248efaba1e7f3f4df46366b25444927b5dafd8e3326fe6da16cadce9813829bf159c952d1eb44077414a95a852b6d94fcfb

test:
  secret_key_base: 9986e333d37339a58d178bc662fe5057b8a8ffdf038a9a2b3200a4a24debfb9900cd7ed2e49e8f7f3338010a83f89010410cb0dbb56cf88a1c232988348c3eaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
